# Generated by Django 6.0.3 on 2026-04-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used to show strike-through old price', max_digits=12, null=True),
        ),
    ]
