# Generated by Django 6.0.3 on 2026-04-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_herocarousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first on the homepage'),
        ),
    ]
